version: '2'

services:
  web:
    image: nginx
    links:
      - fpm
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html

  fpm:
    build: .
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www/html
    links:
      - db:mysql
    user: "${FPM_UID}"

  db:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
