web:
  build: ./docker
  dockerfile: Dockerfile-nginx
  ports:
    - "80:80"
    - "443:443"
  links:
    - fpm
  volumes:
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    - ./src:/var/www

fpm:
  build: ./docker
  dockerfile: Dockerfile-php
  ports:
    - "9000:9000"
  environment:
    - TIMEZONE="America/Sao_Paulo"
  volumes:
    - ./src:/var/www
  links:
    - db:mysql

db:
  image: mariadb
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: example
