web:
  build: .
  ports:
    - "80:80"
    - "443:443"
  links:
    - fpm
  volumes:
    - ./default.conf:/etc/nginx/conf.d/default.conf
    - ./src:/var/www

fpm:
  image: php:fpm
  ports:
    - "9000:9000"
  volumes:
    - ./src:/var/www
